### ISSUE TITLE
Relecture

### ISSUE THREAD

**Issue by GwendolyneFreddy** [Jazira33/SwordCoastStratagems-FR-WIP#1]
Hello !

J'ai re-forké ton repo. Je vais fonctionner composant par composant et t'envoyer une PR par composant relu. Ça en fera beaucoup, mais

1) ça sera moins long et moins fastidieux pour toi de comparer toutes les modifs
2) ça me permettra d'aller vérifier des détails dans les fichiers installés.

La bonne (ou la mauvaise, selon mon humeur) nouvelle, c'est que je commence par les sorts d'IWD. ;)

**Comment by Jazira33** [comment]
D'accord, n'hésite pas à utiliser le lien d'Isaya pour comparer les changements entre la v29 et la v32 obtenu à l'aide de l'outil "TranslationRetriever", tu économiseras un temps précieux. J'ai mis à jours les liens du premier post. Une relecture complète est préférable mais certains fichiers intouchés comme bodhi.tra, caster_shared.tra, demilich.tra, drow.tra, genai.tra, melissan.tra, player1.tra, psionic.tra, sfo.tra, spellholditems.tra, tactical_bg1.tra, tactical_bg2.tra, ulcaster.tra et werewolf.tra peuvent être simplement éfleurés brièvement.

https://www.baldursgateworld.fr/lacouronne/la-chambre-des-scribes/32453-mise-jour-de-la-traduction-fr-de-sword-coast-stratagems-besoin-de-relecteurs.html

Bon courage, je suis là si tu as besoin de quoi que ce soit.

**Comment by GwendolyneFreddy** [comment]
PR avec premiers lots de fichiers relus.
